### ISSUE TITLE
postgres language installation 

### ISSUE THREAD

**Issue by isuftin** [rickatnight11/docker_musicbrainz#3]
You are installing the musicbrainz scripts postgresql-musicbrainz-unaccent and postgresql-musicbrainz-collate @ https://github.com/rickatnight11/docker_musicbrainz/blob/master/musicbrainz-postgres/Dockerfile#L33-L34

However, I don't see where you are adding this to the database via:
- CREATE EXTENSION musicbrainz_unaccent;
- CREATE EXTENSION musicbrainz_collate;

Is this an oversight or am I missing something?

**Comment by rickatnight11** [comment]
I believe the db init/seeding scripts in the musicbrainz container do it,
right? I can check when I get home tonight.

**Comment by rickatnight11** [comment]
Yeah, so according to the install docs (https://github.com/metabrainz/musicbrainz-server/blob/master/INSTALL.md) that step's not needed anymore.  I believe the database import script now installs the extensions.

**Comment by isuftin** [comment]
Interesting! I'll see if I can change my container image to reflect that change and test.
